### ISSUE TITLE
Backup / Restore

### ISSUE THREAD

**Issue by cereyanli** [chris1111/MacBookPro-retina-late-2013#1]
Hi,

I have MacBook Pro (Retina, 15-inch, Late 2013) with Intel Iris Pro on Mac OS BigS Sur ( 11.6.6 ) installed and I have TimeMachine backup activated

as far as I understand your method will work with my Macbook Pro but what is not clear to me whether this is an in place upgrade or it does install fresh Monetary ? If it is a fresh install, can I restore my latest time machine backup right after installation?

Thanks

**Comment by chris1111** [comment]
of course it's a fresh install from Monterey, as far as Time machine is concerned I never use it anyway I don't know if it will work for you the best would be to test the install on an external disk in USB or Thunderbolt

**Comment by cereyanli** [comment]
Thanks @chris1111

**Comment by cereyanli** [comment]
Thanks @chris1111
