### ISSUE TITLE
change the display resolution

### ISSUE THREAD

**Issue by johnfu360** [chris1111/MacBookPro-retina-late-2013#2]
Hello, it seems my MacBook pro-2013 display did not correct, any idea?

**Comment by chris1111** [comment]
This is not usefull infos about the issue

**Comment by johnfu360** [comment]
Sorry, here is the detail, it seems the display info only show 15M at the' about this mac', it seems the graphic card setup is not correct

**Comment by chris1111** [comment]
In Ventura 13 there is no Graphics support for Intel Iris Pro Graphics

**Comment by johnfu360** [comment]
i see, got it, thank you
