### ISSUE TITLE
EFI Monterey 12/EFI/APPLE/UPDATERS/MULTIUPDATER/MultiUpdater.efi flagged as malware 

### ISSUE THREAD

**Issue by obrientg** [chris1111/MacBookPro-retina-late-2013#5]
Hello! 

I submitted the EFI Monterey 12.zip file to VirusTotal and one of the files being used [EFI Monterey 12/EFI/APPLE/UPDATERS/MULTIUPDATER/MultiUpdater.efi] is being flagged as Malware.Win64.Gen.bot!se14502

The full analysis can be found https://www.virustotal.com/gui/file/f11587e13262925575bdb0f60a9d50b8517ef81becc7bcd58f051c2ce4edd39d/details

Any chance of getting a non-infected file used for this project (please)? 

TIA!

**Comment by chris1111** [comment]
The file is non infect its Apple file original

The analiser is `Gidinsoft (No Cloud)` 
other analising OK☑️

**Comment by chris1111** [comment]
Anyway this repos will be archivate its really not usefull 
I upload the EFI folder without Apple/Firmware
